// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	domain "ecomplaint/model/domain"

	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: cat
func (_m *CategoryRepository) Create(cat *domain.Category) (*domain.Category, error) {
	ret := _m.Called(cat)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Category) (*domain.Category, error)); ok {
		return rf(cat)
	}
	if rf, ok := ret.Get(0).(func(*domain.Category) *domain.Category); ok {
		r0 = rf(cat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Category) error); ok {
		r1 = rf(cat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields:
func (_m *CategoryRepository) FindAll() ([]domain.Category, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Category, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Category); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *CategoryRepository) FindById(id string) (*domain.Category, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Category, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Category); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: cat, id
func (_m *CategoryRepository) Update(cat *domain.Category, id string) (*domain.Category, error) {
	ret := _m.Called(cat, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Category, string) (*domain.Category, error)); ok {
		return rf(cat, id)
	}
	if rf, ok := ret.Get(0).(func(*domain.Category, string) *domain.Category); ok {
		r0 = rf(cat, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Category, string) error); ok {
		r1 = rf(cat, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
