// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	domain "ecomplaint/model/domain"

	mock "github.com/stretchr/testify/mock"
)

// AdminRepository is an autogenerated mock type for the AdminRepository type
type AdminRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: admin
func (_m *AdminRepository) Create(admin *domain.Admin) (*domain.Admin, error) {
	ret := _m.Called(admin)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Admin) (*domain.Admin, error)); ok {
		return rf(admin)
	}
	if rf, ok := ret.Get(0).(func(*domain.Admin) *domain.Admin); ok {
		r0 = rf(admin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Admin) error); ok {
		r1 = rf(admin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *AdminRepository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: page, pageSize
func (_m *AdminRepository) FindAll(page int, pageSize int) ([]domain.Admin, int64, error) {
	ret := _m.Called(page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Admin
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int) ([]domain.Admin, int64, error)); ok {
		return rf(page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(int, int) []domain.Admin); ok {
		r0 = rf(page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) int64); ok {
		r1 = rf(page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int) error); ok {
		r2 = rf(page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByEmail provides a mock function with given fields: email
func (_m *AdminRepository) FindByEmail(email string) (*domain.Admin, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Admin, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Admin); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *AdminRepository) FindById(id string) (*domain.Admin, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Admin, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Admin); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: name
func (_m *AdminRepository) FindByName(name string) (*domain.Admin, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Admin, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Admin); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUsername provides a mock function with given fields: username
func (_m *AdminRepository) FindByUsername(username string) (*domain.Admin, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Admin, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Admin); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PhotoProfile provides a mock function with given fields: admin, id
func (_m *AdminRepository) PhotoProfile(admin *domain.Admin, id string) (*domain.Admin, error) {
	ret := _m.Called(admin, id)

	if len(ret) == 0 {
		panic("no return value specified for PhotoProfile")
	}

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Admin, string) (*domain.Admin, error)); ok {
		return rf(admin, id)
	}
	if rf, ok := ret.Get(0).(func(*domain.Admin, string) *domain.Admin); ok {
		r0 = rf(admin, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Admin, string) error); ok {
		r1 = rf(admin, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: admin, id
func (_m *AdminRepository) ResetPassword(admin *domain.Admin, id string) (*domain.Admin, error) {
	ret := _m.Called(admin, id)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Admin, string) (*domain.Admin, error)); ok {
		return rf(admin, id)
	}
	if rf, ok := ret.Get(0).(func(*domain.Admin, string) *domain.Admin); ok {
		r0 = rf(admin, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Admin, string) error); ok {
		r1 = rf(admin, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: admin, id
func (_m *AdminRepository) Update(admin *domain.Admin, id string) (*domain.Admin, error) {
	ret := _m.Called(admin, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.Admin, string) (*domain.Admin, error)); ok {
		return rf(admin, id)
	}
	if rf, ok := ret.Get(0).(func(*domain.Admin, string) *domain.Admin); ok {
		r0 = rf(admin, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.Admin, string) error); ok {
		r1 = rf(admin, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAdminRepository creates a new instance of AdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRepository {
	mock := &AdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
