// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// AIService is an autogenerated mock type for the AIService type
type AIService struct {
	mock.Mock
}

// ResolveComplaint provides a mock function with given fields: ctx, complaint
func (_m *AIService) ResolveComplaint(ctx echo.Context, complaint string) (string, error) {
	ret := _m.Called(ctx, complaint)

	if len(ret) == 0 {
		panic("no return value specified for ResolveComplaint")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) (string, error)); ok {
		return rf(ctx, complaint)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, string) string); ok {
		r0 = rf(ctx, complaint)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(echo.Context, string) error); ok {
		r1 = rf(ctx, complaint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAIService creates a new instance of AIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIService {
	mock := &AIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
