// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NotificationController is an autogenerated mock type for the NotificationController type
type NotificationController struct {
	mock.Mock
}

// FindAllNotification provides a mock function with given fields: ctx
func (_m *NotificationController) FindAllNotification(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationController creates a new instance of NotificationController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationController(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationController {
	mock := &NotificationController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
